# ARRAY OBJECT PROGRAMMING IN NUMPY

In [54]:
import numpy as np

data = np.random.randn(2,3) #generate a 2 by 3 array
print("The array generated is {}".format(data))
print("The shape of data is {}".format(data.shape))
print("The dimension of the array is {}".format(data.ndim))
print("The data type of the array : {}".format(data.dtype))

The array generated is [[-0.00514941  0.13624718 -0.44639368]
 [ 2.23466785  0.3257712   1.18056055]]
The shape of data is (2, 3)
The dimension of the array is 2
The data type of the array : float64


In [55]:
zeros = np.zeros(10)
print("zeros dim : {}".format(zeros.ndim))
print("zeros shape : {}".format(zeros.shape))
print(zeros)

print("-------")

ones = np.ones((2,3)) # pass a tuple
print("ones dim : {}".format(ones.ndim))
print("ones shape : {}".format(ones.shape))
print(ones)

zeros dim : 1
zeros shape : (10,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-------
ones dim : 2
ones shape : (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]]


In [37]:
from_zero_to_nine = np.arange(10)
print(from_zero_to_nine)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
four_times_four = np.eye(4, dtype=int)
print(four_times_four)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [44]:
arr = np.array([1, 2, 3, 4, 5])
print("arr data type: {}.".format(arr.dtype))
print("------")
float_arr = arr.astype(np.float64)
print("data type after the cast : {}".format(float_arr.dtype))

arr data type: int32.
------
data type after the cast : float64


### ARITHMETIC WITH NUMPY ARRAYS

In [53]:
def delimiter():
    print("----------")

arr = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])

print("array is : \n{}".format(arr))
delimiter()
print("the array squared is : \n{}".format(arr**2))
delimiter()
print("the array minus the array is : \n{}".format(arr-arr))
delimiter()
print("The inverse of arr is : \n{}".format(1/arr))
delimiter()
print("The square root of arr is: \n{}".format(arr ** 0.5))


array is : 
[[1. 2. 3.]
 [4. 5. 6.]]
----------
the array squared is : 
[[ 1.  4.  9.]
 [16. 25. 36.]]
----------
the array minus the array is : 
[[0. 0. 0.]
 [0. 0. 0.]]
----------
The inverse of arr is : 
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
----------
The square root of arr is: 
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [58]:
arr = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])

arr2 = np.array([
    [0., 4., 1.],
    [7., 2., 12.]
])

comparison = arr2 > arr
print(comparison)
delimiter()
print("The data type of the comparison array is: {}".format(comparison.dtype))

[[False  True False]
 [ True False  True]]
----------
The data type of the comparison array is: bool
