# INTRODUCTION TO NUMPY

In [1]:
import numpy as np

# ARRAYS

In [11]:
test_scores = np.array([92, 94, 88, 94, 87])
print(test_scores)
print("Object type : {}".format(str(type(test_scores))))

[92 94 88 94 87]
Object type : <class 'numpy.ndarray'>


In [12]:
scores = [92, 94, 88, 94, 87]
scores_array = np.array(scores)
print(scores_array)

[92 94 88 94 87]


# CREATING AN ARRAY FROM AN CSV FILE

In [16]:
gradebooks_array = np.genfromtxt("gradebook.csv", delimiter=',')
print(gradebooks_array)

[[nan nan nan]
 [nan nan 75.]
 [nan nan 82.]
 [nan nan 99.]
 [nan nan 90.]
 [nan nan 72.]
 [nan nan 66.]
 [nan nan 88.]
 [nan nan 82.]
 [nan nan 91.]
 [nan nan 85.]]


# OPERATIONS WITH ARRAYS

In [17]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_1_fixed = test_1 ** 2
test_2_fixed = test_2 // 2
test_3_fixed = test_3 + 2

print(test_1_fixed)
print(test_2_fixed)
print(test_3_fixed)

[8464 8836 7744 8281 7569]
[39 50 43 46 45]
[89 87 74 92 94]


In [18]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
test_3_fixed = test_3 + 2

total_grade = test_1 + test_2 + test_3_fixed 
print("total grade: {}".format(total_grade))

final_grade = total_grade / 3
print("final grade: {}".format(final_grade))

total grade: [260 281 248 276 272]
final grade: [86.66666667 93.66666667 82.66666667 92.         90.66666667]


# TWO-DIMENSIONAL ARRAYS

In [19]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [21]:
tests = np.array([[92, 94, 88, 91, 87], 
                 [79, 100, 86, 93, 91], 
                 [87, 85, 72, 90, 92]])

print(tests)

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]


# SELECTING ELEMENT FOR A 1-D ARRAY

In [22]:
a = np.array([5, 2, 7, 0, 11])
print(a[0])
print(a[0:3])
print(a[:4])
print(a[:-3])

5
[5 2 7]
[5 2 7 0]
[5 2]


# SELECTION ELEMENT FOR A 2-D ARRAY

In [23]:
b = np.array([[32, 15, 6, 9, 14], 
              [12, 10, 5, 23, 1],
              [2, 16, 13, 40, 37]])

print(b[2,1]) #16
print(b[:,0]) # [32, 12, 2]
print(b[1,:]) #[12, 10,  5, 23,  1]

16
[32 12  2]
[12 10  5 23  1]


# LOGICAL OPERATIONS WITH ARRAYS

In [24]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])
print(a>5)

[ True False False False False False  True  True  True  True]


In [25]:
print(a[a>5])

[10  9  8  9  7]


In [27]:
print(a[(a>5)|(a<2)])

[10  9  8  9  7]
